cargo-features = ["edition2024"]

[package]
name = "ConnectFour"
version = "0.1.0"
edition = "2024"

[dependencies]
binary-heap-plus = "0.5.0"
hashbrown = "0.16.1"
paste = "1.0.15"

[profile.dev]
opt-level = 3
overflow-checks = false
